#!/usr/bin/env bash

mkcd() {
    mkdir -p "$1" && cd "$1"
}

file_exists() {
    # variables inside functions have global scope
    
    # makes the variable local to this function 
    local file="$1"
    if [[ -f "$file" ]]; then
        return 0
    else
        return 1
    fi
}

